sudo: required
dist: trusty
services:
 - docker
env:
  global:
   - DOCKER_NAME=fsdn_bot
   - DOCKER_ID=y2khub/fsdn_bot
before_install:
 - openssl aes-256-cbc -K $encrypted_279e43053dd2_key -iv $encrypted_279e43053dd2_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
 - chmod 400 ~/.ssh/id_rsa
 - sudo apt-get update
 - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
script:
 - docker build --rm -f Dockerfile -t $DOCKER_ID .
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 - docker push $DOCKER_ID
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -o "StrictHostKeyChecking=no" $DEPLOY_AUTHORITY "docker pull $DOCKER_ID
    && docker rm -f $DOCKER_NAME || true && docker run --name $DOCKER_NAME -d -e TELEGRAM_TOKEN=$TELEGRAM_TOKEN 
    $DOCKER_ID"
